name: SCA Check - High Severity - GH Actions 
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@master
        
      - name: mkdir for uploaded artifacts
        run: mkdir downloads 
        
      - name: install/auth to Snyk 
        run: 
          npm install snyk -g 
          npm install snyk-to-html -g
          
      - name: run Snyk
        run: snyk test --json | snyk-to-html -o results.html
        continue-on-error: true 
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          
      - name: upload html results artifact
        uses: actions/download-artifact@v3
        with:
          name: upload html results artifacts
        continue-on-error: true
     
